title: Kyle M. Hart
description: >- # this means to ignore newlines until "baseurl:"
  This is my simple website to showcase some of the neat projects that
  I work on and the various tutorials that I use.
# the subpath of your site, e.g. /blog
baseurl: ""
# the base hostname & protocol for your site, e.g. http://example.com
url: "https://kylerobots.github.io"
repository: "kylerobots/kylerobots.github.io"

# Author information
author:
  name: "Kyle M. Hart"
  avatar: "/assets/images/Headshot.jpg"
  bio: "He/Him. A part time PhD candidate and full time robotics lab director."
  location: "New Jersey, USA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:kyle.m.hart@gmail.com"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0001-8254-5722"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=fkaLvH4AAAAJ&hl=en&oi=ao"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kylerobots"

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

collections:
  tutorials:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
      type: tutorials
    values:
      author_profile: true
      layout: single
      share: true
      toc: true
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      layout: single
      read_time: true
      share: true
      show_date: true
      toc: true
